# https://artifacthub.io/packages/helm/prometheus-community/prometheus
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default # ← AppProject 안 쓰는 핵심
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 28.9.0
      helm:
        valueFiles:
          - $values/values/prometheus.yaml

    - repoURL: https://github.com/dr-kube/dr-kube.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      interval: 30s
    syncOptions:
      - CreateNamespace=true
