apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
    {{- range $key, $value := .Values.app.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        {{- range $key, $value := .Values.app.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.app.container.name }}
          image: "{{ .Values.app.container.image }}:{{ .Values.app.container.tag }}"
          {{- if .Values.app.container.command }}
          command:
            {{- toYaml .Values.app.container.command | nindent 12 }}
          {{- end }}
          {{- if .Values.app.container.args }}
          args:
            {{- toYaml .Values.app.container.args | nindent 12 }}
          {{- end }}
          resources:
            requests:
              memory: {{ .Values.app.container.resources.requests.memory | quote }}
              cpu: {{ .Values.app.container.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.app.container.resources.limits.memory | quote }}
              cpu: {{ .Values.app.container.resources.limits.cpu | quote }}
